added CD

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -4,6 +4,68 @@ name: CD
 on:
   push:
     branches:
-      - main
+      - prod
+      - dev
+      - homolog
 
   workflow_dispatch:
+
+jobs:
+  DeployToAWS:
+    environment:
+        name: ${{ github.ref_name }}
+    runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+        - uses: actions/checkout@v2
+
+        - name: Set AWS Account ID
+          run: |
+            if [[ "${{ github.ref_name }}" == "dev" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name!" && exit 1
+            fi
+
+        - name: Setup AWS Credentials
+          uses: aws-actions/configure-aws-credentials@v2
+          with:
+            aws-region: ${{ vars.AWS_REGION }}
+            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+            role-session-name: github-action
+
+        - name: Setting stage and stack name
+          run: |
+            echo "STAGE=${{ github.ref_name }}" 
+            echo "STACK_NAME=PortalEntidadesStack${{github.ref_name}}" >> $GITHUB_ENV
+
+        - uses: actions/checkout@v3
+        - uses: actions/setup-python@v4
+          with:
+            python-version: '3.11'
+
+        - name: Installing Dependencies
+          run: |
+            npm install -g aws-cdk
+            cd iac
+            pip install -r requirements-infra.txt
+
+        - name: DeployWithCDK
+          run: |
+            cd iac
+            cdk synth
+            cdk deploy --require-approval never 
+
+          env:
+              AWS_REGION: ${{ vars.AWS_REGION }}
+              AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+              STACK_NAME: ${{ env.STACK_NAME }}
+              GITHUB_REF_NAME: ${{ github.ref_name }}
+              MSS_NAME: ${{ github.event.repository.name }}
